version: '3.9'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuserpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uappuser", "-pappuserpass"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: shwetathikekar17/flask-mysql-docker:latest
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    
      
volumes:
  mysql-data:
  
